# Generated by Django 2.0.7 on 2018-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_ASSESSMENT', '0002_auto_20181102_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.TextField(null=True),
        ),
    ]
