# Generated by Django 2.0.7 on 2018-11-02 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D_ASSESSMENT', '0003_auto_20181102_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('disaster_type', models.CharField(choices=[('Tornadoes and Severe Storms.', 'Tornadoes and Severe Storms.'), ('Hurricanes and Tropical Storms.', 'Hurricanes and Tropical Storms.'), ('Floods.', 'Floods.'), ('Wildfires.', 'Wildfires.'), ('Earthquakes.', 'Earthquakes.'), ('Drought', 'Drought')], max_length=20)),
                ('alert', models.CharField(choices=[('RED', 1), ('ORANGE', 2), ('YELLOW', 3)], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(choices=[('POLICE', 'Police Station'), ('HOSPITAL', 'Hospital'), ('PANCHAYATH', 'Panchayath'), ('SCHOOL', 'School'), ('FIRE', 'fire station')], max_length=30)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='D_ASSESSMENT.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('post', models.TextField(null=True)),
                ('poppulation', models.IntegerField()),
                ('chief', models.OneToOneField(limit_choices_to={'user_type': 'SUP'}, on_delete=django.db.models.deletion.CASCADE, to='D_ASSESSMENT.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='D_ASSESSMENT.Place'),
        ),
    ]
