# Generated by Django 2.0.7 on 2018-11-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('D_ASSESSMENT', '0004_auto_20181102_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='D_ASSESSMENT.Profile'),
        ),
        migrations.AddField(
            model_name='disaster',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
