# Generated by Django 2.0.7 on 2018-11-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_ASSESSMENT', '0006_disaster_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
